Repository kubernetes-csi/csi-driver-smb, pull requests merged in 2020-10, with the labels that each got.

#126 CI: add `golint` and `misspell` to static checks
  .github/workflows/static.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/XS

#127 Revert "fix: create nonroot user in Dockerfile"
  .github/workflows/darwin.yaml
  .github/workflows/ubuntu.yml
  .github/workflows/windows.yml
  charts/latest/csi-driver-smb/templates/csi-smb-controller.yaml
  charts/latest/csi-driver-smb/templates/csi-smb-node.yaml
  deploy/csi-smb-controller.yaml
  deploy/csi-smb-node.yaml
  pkg/smbplugin/Dockerfile
  pkg/smbplugin/dev.Dockerfile
Labels: approved, cncf-cla: yes, release-note-none, size/S

#128 setup e2e tests in github actions
  .github/workflows/ubuntu-e2e.yml
  Makefile
  test/utils/deploy-kind.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/M

#131 fix: cifs mount broken after driver restart
  charts/latest/csi-driver-smb/templates/csi-smb-node.yaml
  deploy/csi-smb-node.yaml
Labels: approved, cncf-cla: yes, kind/bug, release-note, size/XS

#133 doc: cut v0.4.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/v0.4.0/csi-driver-smb-v0.4.0.tgz
  charts/v0.4.0/csi-driver-smb/Chart.yaml
  charts/v0.4.0/csi-driver-smb/templates/NOTES.txt
  charts/v0.4.0/csi-driver-smb/templates/_helpers.tpl
  charts/v0.4.0/csi-driver-smb/templates/csi-smb-controller.yaml
  charts/v0.4.0/csi-driver-smb/templates/csi-smb-driver.yaml
  charts/v0.4.0/csi-driver-smb/templates/csi-smb-node-windows.yaml
  charts/v0.4.0/csi-driver-smb/templates/csi-smb-node.yaml
  charts/v0.4.0/csi-driver-smb/templates/rbac-csi-smb-controller.yaml
  charts/v0.4.0/csi-driver-smb/values.yaml
  deploy/v0.4.0/csi-smb-controller.yaml
  deploy/v0.4.0/csi-smb-driver.yaml
  deploy/v0.4.0/csi-smb-node-windows.yaml
  deploy/v0.4.0/csi-smb-node.yaml
  deploy/v0.4.0/rbac-csi-smb-controller.yaml
  docs/install-csi-driver-v0.4.0.md
  docs/install-smb-csi-driver.md
Labels: approved, cncf-cla: yes, kind/feature, release-note, size/XXL
