Repository kubernetes-csi/csi-driver-smb, pull requests merged in 2020-11, with the labels that each got.

#139 Add AZURE prefix to e2e environment variables
  test/utils/credentials/credentials.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note, size/S

#143 test: fix integration test failure
  test/integration/run-test.sh
Labels: approved, cncf-cla: yes, kind/failing-test, release-note-none, size/XS

#141 image: support multi OS versions for Windows images
  Makefile
  docs/csi-dev.md
  hack/release-image.sh
  pkg/smbplugin/Windows.Dockerfile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/L

#142 fix: update livenessprobe version from v1.1.0 to v2.0.0
  charts/latest/csi-driver-smb/templates/csi-smb-controller.yaml
  charts/latest/csi-driver-smb/templates/csi-smb-node.yaml
  charts/latest/csi-driver-smb/values.yaml
  deploy/csi-smb-controller.yaml
  deploy/csi-smb-node.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/S

#144 feat: Add ARM64 support
  Makefile
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#147 Fix image repo, version and flag to support ARM64
  charts/latest/csi-driver-smb/templates/csi-smb-controller.yaml
  charts/latest/csi-driver-smb/values.yaml
  deploy/csi-smb-controller.yaml
  deploy/csi-smb-node.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/S

#149 watch windows pods
  docs/install-csi-driver-v0.4.0.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#152 Check isExistsResponse for nil before accessing Exists field
  pkg/mounter/safe_mounter_windows.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#154 feat: add ARM64 image build support
  Makefile
  pkg/smbplugin/amd64.Dockerfile
  pkg/smbplugin/arm64.Dockerfile
Labels: approved, cncf-cla: yes, kind/feature, release-note, size/M

#158 CI: Update golangci/golangci-linter-action to v2
  .github/workflows/static.yaml
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/XS

#157 chore: optimize Makefile
  Makefile
Labels: approved, cncf-cla: yes, kind/cleanup, release-note-none, size/S

#159 Combine arm64.Dockerfile and amd64.Dockerfile
  .github/workflows/ubuntu-e2e.yml
  Makefile
  pkg/smbplugin/Dockerfile
  pkg/smbplugin/arm64.Dockerfile
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/M

#153 doc: cut v0.5.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/v0.5.0/csi-driver-smb-v0.5.0.tgz
  charts/v0.5.0/csi-driver-smb/Chart.yaml
  charts/v0.5.0/csi-driver-smb/templates/NOTES.txt
  charts/v0.5.0/csi-driver-smb/templates/_helpers.tpl
  charts/v0.5.0/csi-driver-smb/templates/csi-smb-controller.yaml
  charts/v0.5.0/csi-driver-smb/templates/csi-smb-driver.yaml
  charts/v0.5.0/csi-driver-smb/templates/csi-smb-node-windows.yaml
  charts/v0.5.0/csi-driver-smb/templates/csi-smb-node.yaml
  charts/v0.5.0/csi-driver-smb/templates/rbac-csi-smb-controller.yaml
  charts/v0.5.0/csi-driver-smb/values.yaml
  deploy/v0.5.0/csi-smb-controller.yaml
  deploy/v0.5.0/csi-smb-driver.yaml
  deploy/v0.5.0/csi-smb-node-windows.yaml
  deploy/v0.5.0/csi-smb-node.yaml
  deploy/v0.5.0/rbac-csi-smb-controller.yaml
  docs/install-csi-driver-v0.5.0.md
  docs/install-smb-csi-driver.md
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/documentation, release-note, size/XXL

#165 chore: upgrade node-driver-registrar version to v2.0.1 on windows
  charts/latest/csi-driver-smb/values.yaml
  deploy/csi-smb-node-windows.yaml
Labels: approved, cncf-cla: yes, kind/feature, release-note, size/XS

#166 fix: copy netapi32.dll from windows-servercore-cache instead of servercore
  pkg/smbplugin/Windows.Dockerfile
Labels: approved, cncf-cla: yes, kind/feature, release-note, size/XS

#167 chore: optimize build
  Makefile
  pkg/smbplugin/Dockerfile
Labels: approved, cncf-cla: yes, kind/feature, release-note-none, size/S

#168 fix: domain issue on Windows
  deploy/example/storageclass-smb.yaml
  pkg/smb/nodeserver.go
Labels: approved, cncf-cla: yes, kind/bug, release-note, size/S
