Repository kubernetes-csi/csi-driver-smb, pull requests merged in 2020-08, with the labels that each got.

#73 build: use docker buildx to build Linux and Windows images
  .travis.yml
  Makefile
  hack/verify-golint.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/S

#75 fix: initial delay(5s) when mounting smb file
  deploy/example/smb-provisioner/smb-server.yaml
  pkg/smb/nodeserver.go
Labels: approved, cncf-cla: yes, kind/bug, release-note, size/XS

#76 fix: password logging issue in Windows node driver logs
  pkg/smb/nodeserver.go
Labels: approved, cncf-cla: yes, kind/bug, release-note, size/M

#77 fix: mkdir error in NodePublishVolume
  Makefile
  pkg/smb/nodeserver.go
Labels: approved, cncf-cla: yes, kind/bug, release-note, size/S

#80 test: add e2e test manifest file
  test/e2e/dynamic_provisioning_test.go
  test/e2e/manifests/linux.json
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, release-note-none, size/M

#81 test: Install SMB provisioner in e2e test
  Makefile
  charts/README.md
  charts/index.yaml
  charts/latest/csi-driver-smb/templates/csi-smb-controller.yaml
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, release-note-none, size/M

#83 chore: reduce the CPU/Memory and ignore the NotFound error
  charts/latest/csi-driver-smb/templates/csi-smb-controller.yaml
  charts/latest/csi-driver-smb/templates/csi-smb-node-windows.yaml
  charts/latest/csi-driver-smb/templates/csi-smb-node.yaml
  deploy/csi-smb-controller.yaml
  deploy/csi-smb-node-windows.yaml
  deploy/csi-smb-node.yaml
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, kind/bug, kind/flake, lgtm, ok-to-test, release-note-none, size/M

#84 test: add multi pods e2e test
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_collocated_pod_tester.go
Labels: approved, cncf-cla: yes, release-note-none, size/L

#85 test: add read-only e2e test
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go
Labels: approved, cncf-cla: yes, release-note-none, size/M

#87 chore: port num change
  charts/latest/csi-driver-smb/templates/csi-smb-controller.yaml
  charts/latest/csi-driver-smb/templates/csi-smb-node-windows.yaml
  charts/latest/csi-driver-smb/templates/csi-smb-node.yaml
  deploy/csi-smb-controller.yaml
  deploy/csi-smb-node-windows.yaml
  deploy/csi-smb-node.yaml
Labels: approved, cncf-cla: yes, release-note, size/M

#88 test: fix windows e2e test failure
  test/e2e/dynamic_provisioning_test.go
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#89 test: add createSubDir e2e test
  pkg/smb/nodeserver.go
  pkg/smb/smb_common_darwin.go
  pkg/smb/smb_common_linux.go
  pkg/smb/smb_common_windows.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, release-note-none, size/M

#90 test: add delete pod e2e test
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
Labels: approved, cncf-cla: yes, release-note-none, size/L

#91 test: add reclaim policy e2e test
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_pod_with_multiple_pv.go
  test/e2e/testsuites/dynamically_provisioned_reclaim_policy_tester.go
  test/e2e/testsuites/specs.go
Labels: approved, cncf-cla: yes, release-note-none, size/L

#92 doc: cut v0.3.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/v0.3.0/csi-driver-smb-v0.3.0.tgz
  charts/v0.3.0/csi-driver-smb/Chart.yaml
  charts/v0.3.0/csi-driver-smb/templates/NOTES.txt
  charts/v0.3.0/csi-driver-smb/templates/_helpers.tpl
  charts/v0.3.0/csi-driver-smb/templates/csi-smb-controller.yaml
  charts/v0.3.0/csi-driver-smb/templates/csi-smb-driver.yaml
  charts/v0.3.0/csi-driver-smb/templates/csi-smb-node-windows.yaml
  charts/v0.3.0/csi-driver-smb/templates/csi-smb-node.yaml
  charts/v0.3.0/csi-driver-smb/templates/rbac-csi-smb-controller.yaml
  charts/v0.3.0/csi-driver-smb/values.yaml
  deploy/v0.3.0/csi-smb-controller.yaml
  deploy/v0.3.0/csi-smb-driver.yaml
  deploy/v0.3.0/csi-smb-node-windows.yaml
  deploy/v0.3.0/csi-smb-node.yaml
  deploy/v0.3.0/rbac-csi-smb-controller.yaml
  docs/install-csi-driver-v0.3.0.md
  docs/install-smb-csi-driver.md
Labels: approved, cncf-cla: yes, kind/documentation, release-note, size/XL

#93 test: enable more sanity tests
  test/sanity/run-test.sh
Labels: approved, cncf-cla: yes, release-note-none, size/XS

#96 feat: Add imagePullSecrets in Helm chart for secret used to pull Docker images
  charts/README.md
  charts/latest/csi-driver-smb/templates/_helpers.tpl
  charts/latest/csi-driver-smb/templates/csi-smb-controller.yaml
  charts/latest/csi-driver-smb/templates/csi-smb-node-windows.yaml
  charts/latest/csi-driver-smb/templates/csi-smb-node.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/S

#97 test: run e2e test on containerd
  test/e2e/manifest/linux.json
  test/utils/smb_log.sh
Labels: approved, cncf-cla: yes, kind/cleanup, release-note-none, size/XS

#98 test: fix PULL_REQUEST_TEMPLATE
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, kind/documentation, release-note-none, size/XS

#99 test: add metrics logging in e2e test
  Makefile
  charts/README.md
  charts/latest/csi-driver-smb/templates/csi-smb-controller.yaml
  charts/latest/csi-driver-smb/templates/csi-smb-node-windows.yaml
  charts/latest/csi-driver-smb/templates/csi-smb-node.yaml
  charts/latest/csi-driver-smb/values.yaml
  deploy/csi-smb-controller.yaml
  deploy/csi-smb-node-windows.yaml
  deploy/csi-smb-node.yaml
  deploy/example/metrics/README.md
  deploy/example/metrics/csi-smb-controller-svc.yaml
  hack/verify-yamllint.sh
  pkg/smbplugin/main.go
  test/e2e/suite_test.go
  test/utils/smb_log.sh
Labels: approved, cncf-cla: yes, release-note-none, size/M
