Repository kubernetes-csi/csi-driver-smb, pull requests merged in 2020-09, with the labels that each got.

#100 fix: Update debian base image to v2.1.3
  pkg/smbplugin/Dockerfile
Labels: approved, cncf-cla: yes, kind/bug, release-note, size/XS

#101 Skip unit tests in windows
  pkg/smb/nodeserver_test.go
  pkg/smb/smb_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/S

#102 add Windows unit test pipeline
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/workflows/windows.yml
  pkg/mounter/safe_mounter_windows.go
Labels: approved, cncf-cla: yes, release-note-none, size/S

#104 test: fix windows unit test
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/windows.yml
  pkg/smb/nodeserver_test.go
  pkg/smb/smb_test.go
Labels: approved, cncf-cla: yes, release-note-none, size/M

#105 move integration tests into github workflows
  .github/workflows/go.yml
  .github/workflows/windows.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/M

#111 test: add darwin support
  .github/workflows/darwin.yaml
  .github/workflows/ubuntu.yml
  .github/workflows/windows.yml
  Makefile
  pkg/smb/smb_common_darwin.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/M

#110 make kubelet path configurable from helm values
  charts/README.md
  charts/latest/csi-driver-smb/templates/csi-smb-node-windows.yaml
  charts/latest/csi-driver-smb/templates/csi-smb-node.yaml
  charts/latest/csi-driver-smb/values.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note, size/S

#112 replace all `golang.org/x/net/context` with context
  pkg/csi-common/controllerserver-default.go
  pkg/csi-common/identityserver-default.go
  pkg/csi-common/nodeserver-default.go
  pkg/csi-common/utils.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/XS

#113 test: add csi-proxy-v0.1.0 test config
  test/e2e/manifest/linux.json
  test/e2e/manifest/windows.json
Labels: approved, cncf-cla: yes, kind/failing-test, release-note-none, size/M

#115 test: Fix `TestNodeStageVolume` on Windows
  pkg/smb/fake_mounter_test.go
  pkg/smb/nodeserver.go
  pkg/smb/nodeserver_test.go
  test/utils/testutil/testutil.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/L

#106 chore: upgrade to csi-proxy v0.2.0 beta
  go.mod
  go.sum
  vendor/github.com/kubernetes-csi/csi-proxy/client/go.mod
  vendor/github.com/kubernetes-csi/csi-proxy/client/go.sum
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/M

#117 test: switch to use mcr nginx image
  Makefile
  deploy/example/deployment.yaml
  deploy/example/nginx-pod-smb.yaml
  deploy/example/statefulset.yaml
  hack/verify-golint.sh
  test/e2e/suite_test.go
  test/utils/smb_log.sh
Labels: approved, cncf-cla: yes, kind/documentation, release-note, size/M

#119 CI: Use `golangci-lint-action` for running linters
  .github/workflows/static.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/S

#122 Lay foundations for re-enabling windows tests: Start CSI-Proxy as a background Job.
  .github/workflows/windows.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/S

#123 test: enable windows unit tests with `csi-proxy.exe`
  .github/workflows/windows.yml
  pkg/smb/fake_mounter.go
  pkg/smb/nodeserver_test.go
  pkg/smb/smb_test.go
  test/utils/testutil/testutil.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/L

#124 fix: create nonroot user in Dockerfile
  .github/workflows/darwin.yaml
  .github/workflows/ubuntu.yml
  .github/workflows/windows.yml
  charts/latest/csi-driver-smb/templates/csi-smb-controller.yaml
  charts/latest/csi-driver-smb/templates/csi-smb-node.yaml
  deploy/csi-smb-controller.yaml
  deploy/csi-smb-node.yaml
  pkg/smbplugin/Dockerfile
  pkg/smbplugin/dev.Dockerfile
Labels: approved, cncf-cla: yes, kind/bug, release-note, size/S
