Repository kubernetes-csi/csi-driver-smb, pull requests merged in 2020-07, with the labels that each got.

#50 test: Add unit tests
  pkg/csi-common/controllerserver-default_test.go
  pkg/csi-common/server.go
  pkg/csi-common/server_test.go
  pkg/csi-common/utils.go
  pkg/mounter/safe_mounter_unix_test.go
  pkg/smb/controllerserver_test.go
  pkg/smb/nodeserver_test.go
  pkg/smb/smb.go
  pkg/smb/smb_test.go
  pkg/smbplugin/main.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/XL

#53 fix: installation issue
  deploy/csi-smb-node-windows.yaml
  deploy/csi-smb-node.yaml
  deploy/install-driver.sh
Labels: approved, cncf-cla: yes, kind/bug, release-note-none, size/XS

#55 test: Add unit test for nodeserver
  pkg/smb/fake_mounter.go
  pkg/smb/fake_mounter_test.go
  pkg/smb/nodeserver.go
  pkg/smb/nodeserver_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/XL

#57 chore: move to klog/v2
  deploy/example/smb-provisioner/smb-server.yaml
  go.mod
  pkg/csi-common/controllerserver-default.go
  pkg/csi-common/driver.go
  pkg/csi-common/identityserver-default.go
  pkg/csi-common/nodeserver-default.go
  pkg/csi-common/server.go
  pkg/csi-common/utils.go
  pkg/csi-common/utils_test.go
  pkg/mounter/safe_mounter_windows.go
  pkg/smb/controllerserver.go
  pkg/smb/identityserver.go
  pkg/smb/nodeserver.go
  pkg/smb/smb.go
  pkg/smb/smb_common_windows.go
  pkg/smbplugin/main.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, release-note-none, size/M

#58 chore: move to csi-v1.3.0
  go.mod
  go.sum
  pkg/smb/controllerserver.go
  pkg/smb/controllerserver_test.go
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, release-note, size/XXL

#59 chore: add hack/release-image.sh
  Makefile
  hack/release-image.sh
Labels: approved, cncf-cla: yes, kind/feature, release-note-none, size/M

#61 feat: Storage class support
  Makefile
  README.md
  deploy/csi-smb-controller.yaml
  deploy/example/e2e_usage.md
  deploy/example/pv-smb.yaml
  deploy/example/pvc-smb-csi.yaml
  deploy/example/pvc-smb-static.yaml
  deploy/example/smb-provisioner/README.md
  deploy/example/statefulset.yaml
  deploy/example/storageclass-smb.yaml
  deploy/install-driver.sh
  deploy/rbac-csi-smb-controller.yaml
  deploy/uninstall-driver.sh
  docs/driver-parameters.md
  pkg/smb/controllerserver.go
  pkg/smb/smb.go
  pkg/smbplugin/dev.Dockerfile
  test/sanity/run-test.sh
Labels: approved, cncf-cla: yes, kind/feature, release-note, size/L

#62 test: Update samba docker image
  test/integration/run-test.sh
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/XS

#63 feat: support dynamic provisioning
  deploy/example/e2e_usage.md
  deploy/example/pvc-smb.yaml
  deploy/example/storageclass-smb.yaml
  pkg/smb/nodeserver.go
  pkg/smb/smb.go
  test/integration/run-test.sh
Labels: approved, cncf-cla: yes, kind/feature, release-note, size/M

#65 doc: update samba server doc
  deploy/example/e2e_usage.md
  deploy/example/smb-provisioner/README.md
  deploy/example/smb-provisioner/smb-server-azuredisk.yaml
  hack/release-image.sh
Labels: approved, cncf-cla: yes, kind/documentation, release-note-none, size/L

#66 feat: cut v0.2.0 release
  README.md
  deploy/v0.2.0/csi-smb-controller.yaml
  deploy/v0.2.0/csi-smb-driver.yaml
  deploy/v0.2.0/csi-smb-node-windows.yaml
  deploy/v0.2.0/csi-smb-node.yaml
  deploy/v0.2.0/rbac-csi-smb-controller.yaml
  docs/install-csi-driver-v0.2.0.md
  docs/install-smb-csi-driver.md
Labels: approved, cncf-cla: yes, kind/feature, release-note, size/L

#67 feat: Add helm installation
  charts/README.md
  charts/index.yaml
  charts/latest/csi-driver-smb/Chart.yaml
  charts/latest/csi-driver-smb/templates/NOTES.txt
  charts/latest/csi-driver-smb/templates/_helpers.tpl
  charts/latest/csi-driver-smb/templates/csi-smb-controller.yaml
  charts/latest/csi-driver-smb/templates/csi-smb-driver.yaml
  charts/latest/csi-driver-smb/templates/csi-smb-node-windows.yaml
  charts/latest/csi-driver-smb/templates/csi-smb-node.yaml
  charts/latest/csi-driver-smb/templates/rbac-csi-smb-controller.yaml
  charts/latest/csi-driver-smb/values.yaml
  charts/v0.1.0/csi-driver-smb/Chart.yaml
  charts/v0.1.0/csi-driver-smb/templates/NOTES.txt
  charts/v0.1.0/csi-driver-smb/templates/_helpers.tpl
  charts/v0.1.0/csi-driver-smb/templates/csi-smb-driver.yaml
  charts/v0.1.0/csi-driver-smb/templates/csi-smb-node-windows.yaml
  charts/v0.1.0/csi-driver-smb/templates/csi-smb-node.yaml
  charts/v0.1.0/csi-driver-smb/values.yaml
  charts/v0.2.0/csi-driver-smb-v0.2.0.tgz
  charts/v0.2.0/csi-driver-smb/Chart.yaml
  charts/v0.2.0/csi-driver-smb/templates/NOTES.txt
  charts/v0.2.0/csi-driver-smb/templates/_helpers.tpl
  charts/v0.2.0/csi-driver-smb/templates/csi-smb-controller.yaml
  charts/v0.2.0/csi-driver-smb/templates/csi-smb-driver.yaml
  charts/v0.2.0/csi-driver-smb/templates/csi-smb-node-windows.yaml
  charts/v0.2.0/csi-driver-smb/templates/csi-smb-node.yaml
  charts/v0.2.0/csi-driver-smb/templates/rbac-csi-smb-controller.yaml
  charts/v0.2.0/csi-driver-smb/values.yaml
  hack/verify-helm-chart.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/XXL

#68 test: add helm chart verification
  hack/verify-all.sh
Labels: approved, cncf-cla: yes, release-note-none, size/XS
