Repository kubernetes-csi/csi-driver-smb, pull requests merged in 2020-05, with the labels that each got.

#14 chore: repo rename
  .travis.yml
  Makefile
  deploy/example/e2e_usage.md
  deploy/example/windows/README.md
  deploy/install-driver.sh
  deploy/uninstall-driver.sh
  docs/csi-dev.md
  docs/install-csi-driver-master.md
  go.mod
  pkg/smb/smb.go
  pkg/smb/smb_common_windows.go
  pkg/smbplugin/main.go
  test/sanity/sanity_test.go
  test/utils/credentials/credentials.go
Labels: approved, cncf-cla: yes, kind/cleanup, release-note-none, size/M

#17 README:Fix broken link
  README.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#18 Fix username and password exposed in logs
  pkg/smb/nodeserver.go
  pkg/smb/nodeserver_test.go
  pkg/smb/smb_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/L

#20 test: add test coverage workflow
  .github/workflows/go.yml
Labels: approved, cncf-cla: yes, release-note-none, size/M

#5 test: Enable golint check in travis
  hack/verify-all.sh
  pkg/smb/nodeserver.go
Labels: approved, cncf-cla: yes, release-note-none, size/XS
