Repository kubernetes-csi/csi-driver-smb, pull requests merged in 2020-06, with the labels that each got.

#24 doc: switch to use mcr image
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  deploy/csi-smb-node-windows.yaml
  deploy/csi-smb-node.yaml
  docs/csi-dev.md
Labels: approved, cncf-cla: yes, kind/documentation, release-note-none, size/S

#26 doc: cut v0.1.0
  Makefile
  deploy/v0.1.0/csi-smb-node-windows.yaml
  deploy/v0.1.0/csi-smb-node.yaml
Labels: approved, cncf-cla: yes, kind/documentation, release-note-none, size/XS

#27 Docker: Update base image with debian-base
  pkg/smbplugin/Dockerfile
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/S

#31 Delete common crd-csi-node-info.yaml
  deploy/crd-csi-node-info.yaml
  deploy/install-driver.sh
  deploy/uninstall-driver.sh
  deploy/v0.1.0/crd-csi-node-info.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#33 feat: windows mount issue
  pkg/smb/nodeserver.go
  pkg/smb/smb_common_linux.go
  pkg/smb/smb_common_windows.go
Labels: approved, cncf-cla: yes, kind/feature, release-note, size/S

#35 doc: change Windows docs
  deploy/csi-smb-node-windows.yaml
  deploy/csi-smb-node.yaml
  deploy/example/e2e_usage.md
  deploy/example/windows/README.md
  deploy/install-driver.sh
  docs/install-csi-driver-master.md
  pkg/smb/nodeserver.go
  pkg/smb/smb_common_linux.go
  pkg/smb/smb_common_windows.go
Labels: approved, cncf-cla: yes, kind/documentation, release-note-none, size/M

#34 test: enable integration test
  .travis.yml
  Makefile
  test/integration/run-test.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#40 fix: use MountSensitive to prevent password logging leak
  pkg/smb/nodeserver.go
  pkg/smb/smb_common_linux.go
  pkg/smb/smb_common_windows.go
Labels: approved, cncf-cla: yes, kind/bug, release-note, size/S

#41 fix: Domain is not properly parameterized
  pkg/smb/nodeserver.go
Labels: approved, cncf-cla: yes, kind/bug, release-note-none, size/S

#42 test: refine integration test and add docs
  .travis.yml
  test/integration/README.md
  test/integration/run-test.sh
Labels: approved, cncf-cla: yes, release-note-none, size/M

#44 test: partially enable sanity test
  Makefile
  pkg/smb/smb.go
  test/sanity/run-test.sh
  test/sanity/run-tests-all-clouds.sh
  test/sanity/sanity_test.go
Labels: approved, release-note-none, size/L

#46 test: enable sanity test
  .travis.yml
  pkg/smb/controllerserver.go
  pkg/smb/nodeserver.go
  test/sanity/README.md
  test/sanity/run-test.sh
Labels: approved, cncf-cla: yes, release-note-none, size/M

#47 chore: fix Makefile
  Makefile
Labels: approved, cncf-cla: yes, release-note-none, size/S

#48 feat: Write a samba server kubernetes deployment
  deploy/example/smb-provisioner/README.md
  deploy/example/smb-provisioner/smb-server-deployment.yaml
  hack/verify-yamllint.sh
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/M
