Repository kubernetes-csi/csi-driver-smb, pull requests merged in 2021-02, with the labels that each got.

#220 Update windows CSI support link
  deploy/example/windows/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#223 add runOnMaster switch for helm chart
  charts/README.md
  charts/latest/csi-driver-smb-v0.7.0.tgz
  charts/latest/csi-driver-smb/templates/csi-smb-controller.yaml
  charts/latest/csi-driver-smb/values.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/XS

#224 test: add verify-helm-chart-files.sh
  charts/index.yaml
  hack/verify-all.sh
  hack/verify-helm-chart-files.sh
  hack/verify-helm-chart.sh
Labels: approved, cncf-cla: yes, kind/cleanup, release-note-none, size/L

#227 test: set lower log level in e2e test
  Makefile
  charts/README.md
  charts/latest/csi-driver-smb-v0.7.0.tgz
  charts/latest/csi-driver-smb/Chart.yaml
  charts/latest/csi-driver-smb/templates/NOTES.txt
  charts/latest/csi-driver-smb/templates/_helpers.tpl
  charts/latest/csi-driver-smb/templates/csi-smb-controller.yaml
  charts/latest/csi-driver-smb/templates/csi-smb-driver.yaml
  charts/latest/csi-driver-smb/templates/csi-smb-node-windows.yaml
  charts/latest/csi-driver-smb/templates/csi-smb-node.yaml
  charts/latest/csi-driver-smb/templates/rbac-csi-smb-controller.yaml
  charts/latest/csi-driver-smb/values.yaml
  pkg/csi-common/utils.go
  pkg/csi-common/utils_test.go
  test/e2e/dynamic_provisioning_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, release-note-none, size/L

#225 Add tolerance to Windows node no schedule taint
  Makefile
  charts/latest/csi-driver-smb-v0.7.0.tgz
  charts/latest/csi-driver-smb/templates/csi-smb-node-windows.yaml
  deploy/csi-smb-node-windows.yaml
  pkg/csi-common/utils.go
  pkg/csi-common/utils_test.go
Labels: cncf-cla: yes, kind/bug, ok-to-test, release-note-none, size/S

#230 test: add helm chart index verification
  hack/verify-helm-chart-files.sh
Labels: approved, cncf-cla: yes, kind/cleanup, release-note-none, size/XS

#231 doc: add mount error on windows doc
  deploy/example/windows/README.md
  deploy/example/windows/deployment.yaml
  deploy/example/windows/statefulset.yaml
  known-issues.md
Labels: approved, cncf-cla: yes, kind/documentation, release-note-none, size/S
