Repository kubernetes-csi/csi-driver-smb, pull requests merged in 2021-01, with the labels that each got.

#190 feat: switch to csi-proxy beta API
  charts/latest/csi-driver-smb/templates/csi-smb-node-windows.yaml
  deploy/csi-smb-node-windows.yaml
  go.mod
  go.sum
  pkg/mounter/safe_mounter_windows.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/filesystem/v1beta1/api.pb.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/filesystem/v1beta1/api.proto
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/smb/v1beta1/api.pb.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/api/smb/v1beta1/api.proto
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/filesystem/v1beta1/client_generated.go
  vendor/github.com/kubernetes-csi/csi-proxy/client/groups/smb/v1beta1/client_generated.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, release-note, size/L

#192 fix: buildkit error in building arm64 image
  Makefile
Labels: approved, cncf-cla: yes, kind/bug, release-note, size/XS

#194 test: enable GH actions on all branches
  .github/workflows/darwin.yaml
  .github/workflows/ubuntu.yml
  .github/workflows/windows.yml
Labels: approved, cncf-cla: yes, kind/cleanup, release-note-none, size/S

#197 test: switch to use go 1.15
  .github/workflows/darwin.yaml
  .github/workflows/linux.yaml
  .github/workflows/ubuntu-e2e.yml
  .github/workflows/windows.yaml
  charts/README.md
Labels: approved, cncf-cla: yes, kind/cleanup, release-note-none, size/S

#201 Remove security context with "privileged: true" setting on Windows node
  charts/latest/csi-driver-smb/templates/csi-smb-node-windows.yaml
  deploy/csi-smb-node-windows.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note, size/XS

#205 chore: remove klogv1 in go mod
  go.mod
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/cleanup, release-note-none, size/XS

#204 test: automate example verification test
  Makefile
  deploy/example/deployment.yaml
  deploy/example/statefulset-nonroot.yaml
  hack/verify-examples.sh
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, release-note-none, size/L

#207 chore: switch to klog 2.4.0
  go.mod
  go.sum
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/go.mod
  vendor/github.com/go-logr/logr/logr.go
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/SECURITY.md
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/cleanup, release-note-none, size/XL

#209 fix: Handle concurrent operation of NodeUnstage with NodeStage and NodeUnpublish with NodePublish
  pkg/smb/nodeserver.go
  pkg/smb/nodeserver_test.go
  pkg/smb/smb.go
  pkg/smb/volume_lock.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/L

#210 test: refactor example verification test
  Makefile
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, release-note-none, size/XS

#206 test: Add restart driver e2e test
  test/e2e/dynamic_provisioning_test.go
  test/e2e/suite_test.go
  test/e2e/testsuites/dynamically_provisioned_restart_driver_tester.go
  test/utils/restart_driver_daemonset.sh
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note-none, size/L

#212 fix: reduce driver logs
  charts/latest/csi-driver-smb/templates/csi-smb-controller.yaml
  charts/latest/csi-driver-smb/templates/csi-smb-node-windows.yaml
  charts/latest/csi-driver-smb/templates/csi-smb-node.yaml
  deploy/csi-smb-controller.yaml
  deploy/csi-smb-node-windows.yaml
  deploy/csi-smb-node.yaml
  hack/verify-examples.sh
  pkg/csi-common/controllerserver-default.go
  pkg/csi-common/identityserver-default.go
  pkg/csi-common/nodeserver-default.go
  pkg/csi-common/utils.go
  pkg/csi-common/utils_test.go
Labels: approved, cncf-cla: yes, kind/bug, release-note, size/M

#213 chore: upgrade livenessprobe to v2.2.0
  charts/latest/csi-driver-smb/values.yaml
  deploy/csi-smb-controller.yaml
  deploy/csi-smb-node-windows.yaml
  deploy/csi-smb-node.yaml
  deploy/example/windows/README.md
Labels: approved, cncf-cla: yes, kind/feature, release-note-none, size/S

#215 cleanup: remove useless logs
  pkg/smb/identityserver.go
Labels: approved, cncf-cla: yes, kind/cleanup, release-note-none, size/XS

#216 fix: Use new windows server image to avoid driver daemonset failure
  test/e2e/manifest/windows.json
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/XS

#217 fix: add latest helm chart file
  .gitignore
  charts/index.yaml
  charts/latest/csi-driver-smb-v0.7.0.tgz
  charts/latest/csi-driver-smb/Chart.yaml
  hack/verify-helm-chart.sh
Labels: approved, cncf-cla: yes, kind/bug, release-note, size/S

#218 fix: update tgz chart files
  charts/v0.2.0/csi-driver-smb-v0.2.0.tgz
  charts/v0.6.0/csi-driver-smb-v0.6.0.tgz
  hack/verify-helm-chart.sh
Labels: approved, cncf-cla: yes, kind/bug, release-note-none, size/S
