Repository kubernetes-csi/csi-driver-smb, pull requests merged in 2021-05, with the labels that each got.

#258 add a new helm parameter for livenessProbe health port
  charts/README.md
  charts/latest/csi-driver-smb-v0.7.0.tgz
  charts/latest/csi-driver-smb/templates/csi-smb-node.yaml
  charts/latest/csi-driver-smb/values.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note-none, size/XS

#260 Add --drivername option for alternative driver deployments
  charts/latest/csi-driver-smb-v0.7.0.tgz
  charts/latest/csi-driver-smb/templates/csi-smb-driver.yaml
  charts/latest/csi-driver-smb/templates/csi-smb-node-windows.yaml
  charts/latest/csi-driver-smb/templates/csi-smb-node.yaml
  charts/latest/csi-driver-smb/values.yaml
  pkg/smb/smb.go
  pkg/smb/smb_test.go
  pkg/smb/version.go
  pkg/smb/version_test.go
  pkg/smbplugin/main.go
  test/e2e/driver/smb_driver.go
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note-none, size/M

#262 chore: upgrade base image to fix CVE issue
  pkg/smbplugin/Dockerfile
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, kind/bug, release-note, size/S

#264 cleanup secret before create a new one
  Makefile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/XS

#266 doc: adjust kubelet chart config
  charts/README.md
  charts/latest/csi-driver-smb-v0.7.0.tgz
  charts/latest/csi-driver-smb/templates/csi-smb-node-windows.yaml
  charts/latest/csi-driver-smb/templates/csi-smb-node.yaml
  charts/latest/csi-driver-smb/values.yaml
Labels: approved, cncf-cla: yes, kind/documentation, release-note-none, size/M

#268 fix: set "host is down" as corrupted mount
  Makefile
  go.mod
  go.sum
  vendor/k8s.io/mount-utils/mount_helper_common.go
  vendor/k8s.io/mount-utils/mount_helper_unix.go
  vendor/k8s.io/mount-utils/mount_helper_windows.go
  vendor/k8s.io/mount-utils/resizefs_linux.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/bug, release-note, size/L

#270 fix: remove unnecessary lock in NodePublish
  pkg/smb/nodeserver.go
  pkg/smb/nodeserver_test.go
Labels: approved, cncf-cla: yes, kind/bug, release-note, size/M

#272 Update path in hostPath example
  deploy/example/smb-provisioner/smb-server-lb.yaml
  deploy/example/smb-provisioner/smb-server.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/XS

#273 Update IsRunningInProw check
  test/utils/credentials/credentials.go
  test/utils/testutil/testutil.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/S

#274 test: run 1.21 external test suites
  test/external-e2e/run.sh
  test/external-e2e/testdriver.yaml
Labels: approved, cncf-cla: yes, release-note-none, size/S

#265 Update helm install
  Makefile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/S

#277 fix: unmount stuck issue when smb file share is not found
  pkg/smb/nodeserver.go
  pkg/smb/smb_common_linux.go
Labels: approved, cncf-cla: yes, kind/bug, release-note, size/XS

#278 Add a script to run e2e test
  test/run-e2e-test.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/M

#279 Change samba server yaml using default sc to be more general
  deploy/example/smb-provisioner/README.md
  deploy/example/smb-provisioner/smb-server-networkdisk.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, kind/documentation, lgtm, ok-to-test, release-note-none, size/S

#280 fix: convert source path on Windows
  deploy/example/e2e_usage.md
  pkg/mounter/safe_mounter_windows.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/suite_test.go
Labels: approved, cncf-cla: yes, kind/bug, release-note, size/S
