Repository kubernetes-csi/csi-driver-smb, pull requests merged in 2021-11, with the labels that each got.

#372 fix: increase sidecar container cpu limit
  charts/latest/csi-driver-smb-v1.4.0.tgz
  charts/latest/csi-driver-smb/templates/csi-smb-node-windows.yaml
  charts/latest/csi-driver-smb/values.yaml
  deploy/csi-smb-controller.yaml
  deploy/csi-smb-node-windows.yaml
  deploy/csi-smb-node.yaml
Labels: kind/bug, release-note, approved, cncf-cla: yes, size/S

#375 feat: upgrade sidecar container version to support WS2022
  charts/README.md
  charts/latest/csi-driver-smb-v1.4.0.tgz
  charts/latest/csi-driver-smb/templates/csi-smb-node.yaml
  charts/latest/csi-driver-smb/values.yaml
  deploy/csi-smb-controller.yaml
  deploy/csi-smb-node.yaml
Labels: kind/feature, release-note, approved, cncf-cla: yes, size/S

#377 update livenessprobe to 2.5.0 to add support Windows Server 2022
  deploy/csi-smb-node-windows.yaml
Labels: kind/feature, approved, size/XS, lgtm, ok-to-test, cncf-cla: yes, release-note-none

#378 feat: increase cpu limits
  charts/latest/csi-driver-smb-v1.4.0.tgz
  charts/latest/csi-driver-smb/templates/csi-smb-node-windows.yaml
  charts/latest/csi-driver-smb/templates/csi-smb-node.yaml
  charts/latest/csi-driver-smb/values.yaml
  deploy/csi-smb-controller.yaml
  deploy/csi-smb-node-windows.yaml
  deploy/csi-smb-node.yaml
Labels: kind/feature, size/L, release-note, approved, cncf-cla: yes

#379 Support fsgroup in CSI calls; enable fsgroup e2e tests
  pkg/smb/nodeserver.go
  pkg/smb/smb.go
  test/external-e2e/run.sh
  test/external-e2e/testdriver.yaml
Labels: kind/feature, release-note, approved, lgtm, cncf-cla: yes, size/S

#380 doc: cut v1.4.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/csi-driver-smb-v1.4.0.tgz
  charts/v1.4.0/csi-driver-smb-v1.4.0.tgz
  charts/v1.4.0/csi-driver-smb/Chart.yaml
  charts/v1.4.0/csi-driver-smb/templates/NOTES.txt
  charts/v1.4.0/csi-driver-smb/templates/_helpers.tpl
  charts/v1.4.0/csi-driver-smb/templates/csi-smb-controller.yaml
  charts/v1.4.0/csi-driver-smb/templates/csi-smb-driver.yaml
  charts/v1.4.0/csi-driver-smb/templates/csi-smb-node-windows.yaml
  charts/v1.4.0/csi-driver-smb/templates/csi-smb-node.yaml
  charts/v1.4.0/csi-driver-smb/templates/rbac-csi-smb-controller.yaml
  charts/v1.4.0/csi-driver-smb/values.yaml
  deploy/v1.4.0/csi-smb-controller.yaml
  deploy/v1.4.0/csi-smb-driver.yaml
  deploy/v1.4.0/csi-smb-node-windows.yaml
  deploy/v1.4.0/csi-smb-node.yaml
  deploy/v1.4.0/rbac-csi-smb-controller.yaml
  docs/install-csi-driver-v1.4.0.md
  docs/install-smb-csi-driver.md
Labels: do-not-merge/hold, release-note, approved, size/XXL, cncf-cla: yes, kind/documentation

#382 chore: switch master branch to use v1.5.0
  Makefile
  charts/index.yaml
  charts/latest/csi-driver-smb-v1.4.0.tgz
  charts/latest/csi-driver-smb-v1.5.0.tgz
  charts/latest/csi-driver-smb/Chart.yaml
Labels: size/M, approved, cncf-cla: yes, kind/documentation, release-note-none
