Repository kubernetes-csi/csi-driver-smb, pull requests merged in 2021-12, with the labels that each got.

#384 cleanup: remove hostPath.type setting on Windows daemonset
  charts/latest/csi-driver-smb-v1.5.0.tgz
  charts/latest/csi-driver-smb/templates/csi-smb-node-windows.yaml
  deploy/csi-smb-node-windows.yaml
Labels: approved, size/XS, kind/cleanup, cncf-cla: yes, release-note-none

#386 feat: switch to gcr.io sidecar images for arm64 support
  charts/README.md
  charts/latest/csi-driver-smb-v1.5.0.tgz
  charts/latest/csi-driver-smb/values.yaml
  deploy/csi-smb-controller.yaml
  deploy/csi-smb-node-windows.yaml
  deploy/csi-smb-node.yaml
Labels: kind/feature, size/M, release-note, approved, cncf-cla: yes

#387 fix: v1.4.0 chart
  charts/index.yaml
  charts/v1.4.0/csi-driver-smb-v1.4.0.tgz
  charts/v1.4.0/csi-driver-smb/Chart.yaml
  hack/verify-helm-chart.sh
Labels: kind/bug, size/M, release-note, approved, cncf-cla: yes

#388 cleanup: remove arm64 build workaround
  Makefile
Labels: approved, size/XS, kind/cleanup, cncf-cla: yes, release-note-none

#391 cleanup: remove 1903 1909 2004 Windows image which is end of life
  Makefile
Labels: release-note, approved, size/XS, kind/cleanup, cncf-cla: yes

#392 test: add apiVersion deprecation test
  .github/workflows/pluto.yaml
  Makefile
  test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
Labels: kind/feature, size/M, approved, lgtm, cncf-cla: yes, release-note-none

#394 fix: CVE-2021-43618 in Ubuntu image
  .github/workflows/pluto.yaml
  pkg/smbplugin/Dockerfile
Labels: kind/bug, release-note, approved, size/XS, cncf-cla: yes

#395 fix: CVE-2021-38561 with golang lib
  go.mod
  go.sum
  vendor/golang.org/x/text/encoding/simplifiedchinese/hzgb2312.go
  vendor/golang.org/x/text/internal/language/compact/tables.go
  vendor/golang.org/x/text/internal/language/language.go
  vendor/golang.org/x/text/internal/language/parse.go
  vendor/golang.org/x/text/internal/language/tables.go
  vendor/golang.org/x/text/language/go1_1.go
  vendor/golang.org/x/text/language/go1_2.go
  vendor/golang.org/x/text/language/language.go
  vendor/golang.org/x/text/language/parse.go
  vendor/golang.org/x/text/language/tables.go
  vendor/golang.org/x/text/secure/bidirule/bidirule10.0.0.go
  vendor/golang.org/x/text/secure/bidirule/bidirule9.0.0.go
  vendor/golang.org/x/text/unicode/bidi/bidi.go
  vendor/golang.org/x/text/unicode/bidi/core.go
  vendor/golang.org/x/text/unicode/bidi/tables10.0.0.go
  vendor/golang.org/x/text/unicode/bidi/tables11.0.0.go
  vendor/golang.org/x/text/unicode/bidi/tables12.0.0.go
  vendor/golang.org/x/text/unicode/bidi/tables13.0.0.go
  vendor/golang.org/x/text/unicode/bidi/tables9.0.0.go
  vendor/golang.org/x/text/unicode/norm/tables10.0.0.go
  vendor/golang.org/x/text/unicode/norm/tables11.0.0.go
  vendor/golang.org/x/text/unicode/norm/tables12.0.0.go
  vendor/golang.org/x/text/unicode/norm/tables13.0.0.go
  vendor/golang.org/x/text/unicode/norm/tables9.0.0.go
  vendor/modules.txt
Labels: kind/bug, release-note, approved, lgtm, size/XXL, cncf-cla: yes

#396 Build golangci-lint via go rather than curl | bash
  hack/verify-all.sh
  hack/verify-golint.sh
Labels: approved, lgtm, kind/cleanup, cncf-cla: yes, release-note-none, size/S

#397 cleanup: remove cpu limits
  charts/README.md
  charts/latest/csi-driver-smb-v1.5.0.tgz
  charts/latest/csi-driver-smb/values.yaml
  deploy/csi-smb-controller.yaml
  deploy/csi-smb-node-windows.yaml
  deploy/csi-smb-node.yaml
Labels: release-note, approved, kind/cleanup, cncf-cla: yes, size/S
