Repository kubernetes-csi/csi-driver-smb, pull requests merged in 2022-06, with the labels that each got.

#485 fix: incorrect runOnMaster config
  Makefile
  charts/latest/csi-driver-smb-v1.8.0.tgz
  charts/latest/csi-driver-smb/templates/csi-smb-controller.yaml
  test/external-e2e/run.sh
Labels: kind/bug, release-note, approved, size/XS, cncf-cla: yes

#486 fix: incorrect v1.7.0 image address
  charts/v1.7.0/csi-driver-smb-v1.7.0.tgz
  charts/v1.7.0/csi-driver-smb/values.yaml
  deploy/v1.7.0/csi-smb-controller.yaml
  deploy/v1.7.0/csi-smb-node-windows.yaml
  deploy/v1.7.0/csi-smb-node.yaml
Labels: kind/bug, release-note, approved, cncf-cla: yes, size/S

#487 doc: update csi-proxy install doc
  deploy/example/windows/README.md
  deploy/example/windows/csi-proxy.yaml
Labels: size/M, approved, cncf-cla: yes, kind/documentation, release-note-none

#492 fix: fix affinity indent error 🐞
  charts/index.yaml
  charts/latest/csi-driver-smb-v1.8.0.tgz
  charts/latest/csi-driver-smb/templates/csi-smb-node.yaml
Labels: kind/bug, approved, size/XS, lgtm, ok-to-test, cncf-cla: yes, release-note-none

#488 fix: node.serviceAccount setting in chart config
  charts/index.yaml
  charts/latest/csi-driver-smb-v1.8.0.tgz
  charts/latest/csi-driver-smb/templates/csi-smb-node-windows.yaml
  charts/latest/csi-driver-smb/templates/csi-smb-node.yaml
Labels: kind/feature, approved, size/XS, lgtm, ok-to-test, cncf-cla: yes, release-note-none

#495 feat: enable GetVolumeStats by default
  charts/latest/csi-driver-smb-v1.8.0.tgz
  charts/latest/csi-driver-smb/templates/csi-smb-node-windows.yaml
  charts/latest/csi-driver-smb/values.yaml
  cmd/smbplugin/main.go
Labels: kind/bug, kind/feature, release-note, approved, cncf-cla: yes, size/S

#494 fix: node.serviceAccount setting in chart config on 1.7.0
  charts/v1.7.0/csi-driver-smb-v1.7.0.tgz
  charts/v1.7.0/csi-driver-smb/templates/csi-smb-node-windows.yaml
  charts/v1.7.0/csi-driver-smb/templates/csi-smb-node.yaml
Labels: kind/bug, release-note, approved, cncf-cla: yes, size/S

#498 feat: create subdir if not exists
  docs/driver-parameters.md
  pkg/smb/controllerserver.go
  pkg/smb/controllerserver_test.go
  pkg/smb/smb.go
  pkg/smb/smb_test.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/suite_test.go
Labels: kind/feature, size/L, release-note, approved, cncf-cla: yes

#500 feat: add runOnControlPlane in chart config
  Makefile
  charts/README.md
  charts/latest/csi-driver-smb-v1.8.0.tgz
  charts/latest/csi-driver-smb/templates/csi-smb-controller.yaml
  charts/latest/csi-driver-smb/values.yaml
  test/external-e2e/run.sh
Labels: kind/feature, release-note, approved, cncf-cla: yes, size/S

#503 feat: support pv/pvc metadata for subDir parameter
  charts/latest/csi-driver-smb-v1.8.0.tgz
  charts/latest/csi-driver-smb/templates/csi-smb-controller.yaml
  deploy/csi-smb-controller.yaml
  docs/driver-parameters.md
  pkg/smb/controllerserver.go
  pkg/smb/controllerserver_test.go
  pkg/smb/nodeserver.go
  pkg/smb/nodeserver_test.go
  pkg/smb/smb.go
  pkg/smb/smb_test.go
  test/e2e/suite_test.go
Labels: size/L, release-note, approved, lgtm, cncf-cla: yes

#504 chore: upgrade sidecar image versions
  charts/README.md
  charts/latest/csi-driver-smb-v1.8.0.tgz
  charts/latest/csi-driver-smb/values.yaml
  deploy/csi-smb-controller.yaml
  deploy/csi-smb-node-windows.yaml
  deploy/csi-smb-node.yaml
Labels: kind/feature, release-note, approved, lgtm, cncf-cla: yes, size/S
