Repository kubernetes-csi/csi-driver-smb, pull requests merged in 2022-01, with the labels that each got.

#400 feat: add subDir in storage class parameters
  .github/workflows/static.yaml
  deploy/example/e2e_usage.md
  deploy/example/storageclass-smb.yaml
  docs/driver-parameters.md
  pkg/smb/controllerserver.go
  pkg/smb/controllerserver_test.go
  pkg/smb/nodeserver.go
  pkg/smb/smb.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/suite_test.go
Labels: kind/feature, size/L, release-note, approved, cncf-cla: yes

#401 test: add no subdir creation e2e test
  deploy/example/e2e_usage.md
  deploy/example/storageclass-smb.yaml
  test/e2e/dynamic_provisioning_test.go
  test/e2e/suite_test.go
Labels: approved, kind/cleanup, cncf-cla: yes, release-note-none, size/S

#402 feat: support mountOptions in DeleteVolume
  Makefile
  docs/driver-parameters.md
  pkg/smb/controllerserver.go
  pkg/smb/smb.go
  pkg/smb/smb_test.go
Labels: kind/feature, size/M, release-note, approved, cncf-cla: yes

#403 feat: add workingMountDir in chart config
  charts/README.md
  charts/latest/csi-driver-smb-v1.5.0.tgz
  charts/latest/csi-driver-smb/templates/csi-smb-controller.yaml
  charts/latest/csi-driver-smb/values.yaml
  pkg/smb/controllerserver.go
  pkg/smb/smb.go
  pkg/smb/smb_test.go
  pkg/smbplugin/main.go
  test/e2e/suite_test.go
Labels: kind/feature, size/M, release-note, approved, cncf-cla: yes

#404 fix: ValidateVolumeCapabilities
  .github/workflows/linux.yaml
  .github/workflows/static.yaml
  hack/helm-signing.asc
  hack/verify-helm-chart-files.sh
  pkg/smb/controllerserver.go
Labels: kind/bug, size/M, release-note, approved, cncf-cla: yes

#407 doc: cut v1.5.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/csi-driver-smb-v1.5.0.tgz
  charts/v1.5.0/csi-driver-smb-v1.5.0.tgz
  charts/v1.5.0/csi-driver-smb/Chart.yaml
  charts/v1.5.0/csi-driver-smb/templates/NOTES.txt
  charts/v1.5.0/csi-driver-smb/templates/_helpers.tpl
  charts/v1.5.0/csi-driver-smb/templates/csi-smb-controller.yaml
  charts/v1.5.0/csi-driver-smb/templates/csi-smb-driver.yaml
  charts/v1.5.0/csi-driver-smb/templates/csi-smb-node-windows.yaml
  charts/v1.5.0/csi-driver-smb/templates/csi-smb-node.yaml
  charts/v1.5.0/csi-driver-smb/templates/rbac-csi-smb-controller.yaml
  charts/v1.5.0/csi-driver-smb/values.yaml
  deploy/v1.5.0/csi-smb-controller.yaml
  deploy/v1.5.0/csi-smb-driver.yaml
  deploy/v1.5.0/csi-smb-node-windows.yaml
  deploy/v1.5.0/csi-smb-node.yaml
  deploy/v1.5.0/rbac-csi-smb-controller.yaml
  docs/install-csi-driver-v1.5.0.md
  docs/install-smb-csi-driver.md
Labels: release-note, approved, lgtm, size/XXL, cncf-cla: yes, kind/documentation

#408 chore: switch master branch to use v1.6.0
  Makefile
  charts/index.yaml
  charts/latest/csi-driver-smb-v1.5.0.tgz
  charts/latest/csi-driver-smb-v1.6.0.tgz
  charts/latest/csi-driver-smb/Chart.yaml
Labels: size/M, approved, cncf-cla: yes, kind/documentation, release-note-none

#409 chore: fix arm v7 build issue
  Makefile
Labels: kind/failing-test, approved, size/XS, cncf-cla: yes, release-note-none

#411 feat: upgrade to csi-provisioner v3.1.0
  .github/workflows/static.yaml
  README.md
  charts/README.md
  charts/latest/csi-driver-smb-v1.6.0.tgz
  charts/latest/csi-driver-smb/values.yaml
  deploy/csi-smb-controller.yaml
Labels: kind/feature, approved, lgtm, cncf-cla: yes, release-note-none, size/S

#414 publish image to cloud provider repo
  cloudbuild.yaml
Labels: approved, lgtm, kind/cleanup, cncf-cla: yes, release-note-none, size/S

#412 fix: CVE-2021-3996 in image build
  pkg/smbplugin/Dockerfile
Labels: kind/bug, release-note, approved, size/XS, lgtm, cncf-cla: yes
