Repository kubernetes-csi/csi-driver-smb, pull requests merged in 2022-11, with the labels that each got.

#546 chore: upgrade base image as debian-base:bullseye-v1.4.2
  cmd/smbplugin/Dockerfile
  go.mod
  go.sum
  vendor/golang.org/x/text/AUTHORS
  vendor/golang.org/x/text/CONTRIBUTORS
  vendor/golang.org/x/text/encoding/htmlindex/tables.go
  vendor/golang.org/x/text/encoding/internal/identifier/mib.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/gbk.go
  vendor/golang.org/x/text/internal/language/compact/tables.go
  vendor/golang.org/x/text/internal/language/lookup.go
  vendor/golang.org/x/text/internal/language/parse.go
  vendor/golang.org/x/text/internal/language/tables.go
  vendor/golang.org/x/text/internal/utf8internal/utf8internal.go
  vendor/golang.org/x/text/language/doc.go
  vendor/golang.org/x/text/language/match.go
  vendor/golang.org/x/text/language/parse.go
  vendor/golang.org/x/text/language/tables.go
  vendor/golang.org/x/text/unicode/bidi/core.go
  vendor/golang.org/x/text/unicode/norm/forminfo.go
  vendor/golang.org/x/text/unicode/norm/normalize.go
  vendor/golang.org/x/text/unicode/norm/tables13.0.0.go
  vendor/modules.txt
Labels: kind/feature, approved, size/XXL, cncf-cla: yes, release-note-none

#553 chore: ugprade sidecar images
  charts/latest/csi-driver-smb-v0.0.0.tgz
  charts/latest/csi-driver-smb/values.yaml
  deploy/csi-smb-controller.yaml
  deploy/csi-smb-node-windows.yaml
  deploy/csi-smb-node.yaml
Labels: kind/feature, approved, lgtm, cncf-cla: yes, release-note-none, size/S

#552 doc: install docs updates on Microk8s based Kubernetes
  charts/README.md
  charts/latest/csi-driver-smb-v0.0.0.tgz
  charts/latest/csi-driver-smb/templates/NOTES.txt
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes, kind/documentation, release-note-none
