Repository kubernetes-csi/csi-driver-smb, pull requests merged in 2023-04, with the labels that each got.

#595 cleanup: remove 20H2 windows image build
  Makefile
Labels: approved, size/XS, kind/cleanup, cncf-cla: yes, release-note-none

#596 feat: enable securityContext.seccompProfile
  charts/README.md
  charts/latest/csi-driver-smb-v0.0.0.tgz
  charts/latest/csi-driver-smb/templates/csi-smb-controller.yaml
  charts/latest/csi-driver-smb/templates/csi-smb-node-windows.yaml
  charts/latest/csi-driver-smb/templates/csi-smb-node.yaml
  charts/latest/csi-driver-smb/values.yaml
  deploy/csi-smb-controller.yaml
  deploy/csi-smb-node-windows.yaml
  deploy/csi-smb-node.yaml
Labels: kind/feature, size/M, release-note, approved, cncf-cla: yes

#597 test(e2e): change the storageclass configuration method in the test file
  deploy/example/statefulset-nonroot.yaml
  deploy/example/statefulset.yaml
  deploy/example/windows/statefulset.yaml
Labels: approved, size/XS, lgtm, ok-to-test, kind/cleanup, cncf-cla: yes, release-note-none

#598 cleanup: replace deprecated ioutil method
  pkg/smb/nodeserver.go
  pkg/smb/smb_test.go
  test/utils/credentials/credentials.go
  test/utils/credentials/credentials_test.go
Labels: approved, lgtm, ok-to-test, kind/cleanup, cncf-cla: yes, release-note-none, size/S

#604 fix: set ClusterFirstWithHostNet as default dnsPolicy
  Makefile
  charts/README.md
  charts/latest/csi-driver-smb-v0.0.0.tgz
  charts/latest/csi-driver-smb/templates/csi-smb-controller.yaml
  charts/latest/csi-driver-smb/values.yaml
  deploy/csi-smb-controller.yaml
  deploy/csi-smb-node.yaml
Labels: kind/bug, release-note, approved, cncf-cla: yes, size/S

#601 feat: volume clone from source volume
  deploy/example/pvc-volume-clone.yaml
  pkg/csi-common/driver_test.go
  pkg/csi-common/utils_test.go
  pkg/smb/controllerserver.go
  pkg/smb/controllerserver_test.go
  pkg/smb/smb.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_volume_cloning_tester.go
  test/e2e/testsuites/specs.go
  test/external-e2e/testdriver.yaml
  test/sanity/secrets.yaml
Labels: kind/feature, size/L, approved, lgtm, ok-to-test, cncf-cla: yes, release-note-none
