Repository kubernetes-csi/csi-driver-smb, pull requests merged in 2023-11, with the labels that each got.

#682 chore: refine delete subDir check
  pkg/smb/controllerserver.go
Labels: approved, kind/cleanup, cncf-cla: yes, release-note-none, size/S

#684 feat: switch to bookworm debian base image
  cmd/smbplugin/Dockerfile
  go.mod
  hack/verify-gomod.sh
  vendor/modules.txt
Labels: kind/feature, release-note, approved, size/XS, cncf-cla: yes

#686 doc: cut v1.13.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/csi-driver-smb-v0.0.0.tgz
  charts/v1.13.0/csi-driver-smb-v1.13.0.tgz
  charts/v1.13.0/csi-driver-smb/Chart.yaml
  charts/v1.13.0/csi-driver-smb/templates/NOTES.txt
  charts/v1.13.0/csi-driver-smb/templates/_helpers.tpl
  charts/v1.13.0/csi-driver-smb/templates/csi-proxy-windows.yaml
  charts/v1.13.0/csi-driver-smb/templates/csi-smb-controller.yaml
  charts/v1.13.0/csi-driver-smb/templates/csi-smb-driver.yaml
  charts/v1.13.0/csi-driver-smb/templates/csi-smb-node-windows.yaml
  charts/v1.13.0/csi-driver-smb/templates/csi-smb-node.yaml
  charts/v1.13.0/csi-driver-smb/templates/rbac-csi-smb.yaml
  charts/v1.13.0/csi-driver-smb/values.yaml
  deploy/v1.13.0/csi-smb-controller.yaml
  deploy/v1.13.0/csi-smb-driver.yaml
  deploy/v1.13.0/csi-smb-node-windows.yaml
  deploy/v1.13.0/csi-smb-node.yaml
  deploy/v1.13.0/rbac-csi-smb.yaml
  docs/install-csi-driver-v1.13.0.md
  docs/install-smb-csi-driver.md
Labels: release-note, approved, size/XXL, cncf-cla: yes, kind/documentation

#689 chore: update bug-report.md gcr to registry.k8s
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: approved, size/XS, lgtm, ok-to-test, kind/cleanup, cncf-cla: yes, release-note-none

#685 chore: upgrade sidecar image versions
  charts/README.md
  charts/latest/csi-driver-smb-v0.0.0.tgz
  charts/latest/csi-driver-smb/values.yaml
  deploy/csi-smb-controller.yaml
  deploy/csi-smb-node-windows.yaml
  deploy/csi-smb-node.yaml
Labels: kind/feature, approved, cncf-cla: yes, release-note-none, size/S

#691 test: upgrade golangci/golangci-lint-action to v1.54
  .github/workflows/static.yaml
  .golangci.yml
  cmd/smbplugin/main.go
  pkg/csi-common/server_test.go
  pkg/mounter/safe_mounter_unix.go
  pkg/smb/controllerserver.go
  pkg/smb/fake_mounter.go
  pkg/smb/identityserver.go
  pkg/smb/nodeserver.go
  pkg/smb/smb.go
  pkg/smb/smb_common_linux.go
  test/e2e/driver/smb_driver.go
  test/e2e/testsuites/specs.go
  test/utils/azure/azure_helpers.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes, release-note-none

#692 fix: CVE-2023-5528
  go.mod
  go.sum
  vendor/golang.org/x/time/AUTHORS
  vendor/golang.org/x/time/CONTRIBUTORS
  vendor/golang.org/x/time/rate/rate.go
  vendor/golang.org/x/time/rate/sometimes.go
  vendor/golang.org/x/tools/go/ast/inspector/inspector.go
  vendor/golang.org/x/tools/internal/typeparams/common.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go117.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go118.go
  vendor/k8s.io/mount-utils/mount.go
  vendor/k8s.io/mount-utils/mount_linux.go
  vendor/k8s.io/mount-utils/mount_windows.go
  vendor/modules.txt
Labels: kind/bug, size/XL, release-note, approved, cncf-cla: yes

#696 doc: fix readOnly setting doc
  deploy/example/e2e_usage.md
  deploy/example/nginx-pod-smb.yaml
  deploy/example/pv-smb.yaml
  deploy/example/smb-provisioner/pv-smb-csi.yaml
  deploy/example/statefulset-nonroot.yaml
  deploy/example/statefulset.yaml
Labels: approved, size/XS, cncf-cla: yes, kind/documentation, release-note-none
