Repository kubernetes-csi/csi-driver-smb, pull requests merged in 2023-05, with the labels that each got.

#605 chore: upgrade csi sidecar container images
  charts/latest/csi-driver-smb-v0.0.0.tgz
  charts/latest/csi-driver-smb/values.yaml
  deploy/csi-smb-controller.yaml
  deploy/csi-smb-node-windows.yaml
  deploy/csi-smb-node.yaml
Labels: kind/feature, approved, cncf-cla: yes, release-note-none, size/S

#607 chore: add dependabot
  .github/dependabot.yaml
Labels: approved, kind/cleanup, cncf-cla: yes, release-note-none, size/S

#606 feat: add support for sec=krb5 mounting
  deploy/example/storageclass-smb-krb5.yaml
  docs/driver-parameters.md
  pkg/smb/nodeserver.go
  pkg/smb/nodeserver_test.go
  pkg/smb/smb.go
Labels: kind/feature, size/L, release-note, approved, lgtm, ok-to-test, cncf-cla: yes

#614 replace references of https://storage.googleapis.com/kubernetes-release with https://dl.k8s.io
  test/external-e2e/run.sh
  test/utils/deploy-kind.sh
  test/utils/deploy-minikube.sh
Labels: do-not-merge/release-note-label-needed, kind/deprecation, approved, size/XS, lgtm, ok-to-test, kind/cleanup, cncf-cla: yes

#613 fix: add default krb5 cc path
  cmd/smbplugin/Dockerfile
Labels: kind/bug, release-note, approved, size/XS, lgtm, ok-to-test, cncf-cla: yes

#618 chore: add Dockerfile dependabot
  .github/dependabot.yaml
Labels: approved, size/XS, kind/cleanup, cncf-cla: yes, release-note-none

#624 Cleaning kerberos cache files on unstage phase
  docs/driver-parameters.md
  pkg/smb/nodeserver.go
  pkg/smb/nodeserver_test.go
Labels: kind/feature, size/L, release-note, approved, lgtm, ok-to-test, cncf-cla: yes
