Repository kubernetes-csi/csi-driver-smb, pull requests merged in 2024-08, with the labels that each got.

#815 fix: node kerberos cache volume name
  charts/latest/csi-driver-smb-v0.0.0.tgz
  charts/latest/csi-driver-smb/templates/csi-smb-node.yaml
  charts/v1.14.0/csi-driver-smb-v1.14.0.tgz
  charts/v1.14.0/csi-driver-smb/templates/csi-smb-node.yaml
  charts/v1.15.0/csi-driver-smb-v1.15.0.tgz
  charts/v1.15.0/csi-driver-smb/templates/csi-smb-node.yaml
Labels: kind/bug, release-note, lgtm, ok-to-test, cncf-cla: yes, size/S

#817 test: add default namespace in examples to fix e2e test failure
  Makefile
  deploy/example/cloning/nginx-pod-restored-cloning.yaml
  deploy/example/daemonset-ephemeral.yaml
  deploy/example/deployment.yaml
  deploy/example/nginx-pod-smb.yaml
  deploy/example/pvc-smb-static.yaml
  deploy/example/pvc-smb.yaml
  deploy/example/smb-provisioner/smb-server-lb.yaml
  deploy/example/smb-provisioner/smb-server-networkdisk.yaml
  deploy/example/smb-provisioner/smb-server.yaml
  deploy/example/statefulset-nonroot.yaml
  deploy/example/statefulset.yaml
  deploy/example/windows/deployment.yaml
  deploy/example/windows/statefulset.yaml
  hack/verify-examples.sh
  test/e2e/suite_test.go
Labels: kind/failing-test, size/L, approved, cncf-cla: yes, release-note-none

#819 test: fix external test failure
  Makefile
Labels: kind/failing-test, approved, size/XS, cncf-cla: yes, release-note-none

#820 test: fix windows e2e test failure
  Makefile
  cmd/smbplugin/Dockerfile.Windows
Labels: kind/failing-test, approved, size/XS, cncf-cla: yes, release-note-none

#824 fix: upgrade csi-provisioner to v5.0.2 to fix pv deletion stuck issue
  charts/README.md
  charts/latest/csi-driver-smb-v0.0.0.tgz
  charts/latest/csi-driver-smb/values.yaml
  deploy/csi-smb-controller.yaml
Labels: kind/bug, release-note, approved, size/XS, cncf-cla: yes

#822 test: fix windows test failure2
  Makefile
  cmd/smbplugin/Dockerfile.Windows
  test/e2e/suite_test.go
  test/utils/get_smb_svc_public_ip.sh
  test/utils/smb_log.sh
Labels: size/M, approved, cncf-cla: yes, release-note-none

#825 test: fix windows 2022 test failure
  deploy/example/windows/deployment.yaml
  deploy/example/windows/statefulset.yaml
  test/e2e/dynamic_provisioning_test.go
  test/e2e/suite_test.go
  test/e2e/testsuites/specs.go
  test/e2e/testsuites/testsuites.go
Labels: kind/failing-test, size/M, approved, cncf-cla: yes, release-note-none

#826 cleanup: use one image tag in e2e test
  Makefile
Labels: approved, kind/cleanup, cncf-cla: yes, release-note-none, size/S

#827 fix: bump mount-utils to treat ENODEV error as corrupted mount
  go.mod
  go.sum
  vendor/k8s.io/mount-utils/mount_helper_unix.go
  vendor/modules.txt
Labels: kind/bug, release-note, approved, cncf-cla: yes, size/S

#829 fix: upgrade csi-provisioner to v5.0.2 on v1.15.0 chart
  charts/v1.15.0/csi-driver-smb-v1.15.0.tgz
  charts/v1.15.0/csi-driver-smb/values.yaml
  cmd/smbplugin/main.go
  deploy/v1.15.0/csi-smb-controller.yaml
  pkg/smb/controllerserver.go
  pkg/smb/smb.go
Labels: kind/bug, release-note, approved, cncf-cla: yes, size/S

#832 test: skip one flacky windows test
  test/e2e/dynamic_provisioning_test.go
Labels: kind/failing-test, approved, size/XS, cncf-cla: yes, release-note-none

#833 doc: add support doc
  support.md
Labels: approved, cncf-cla: yes, kind/documentation, release-note-none, size/S
