Repository kubernetes-csi/csi-driver-smb, pull requests merged in 2024-07, with the labels that each got.

#798 test: fix trivy action failure
  .github/workflows/trivy.yaml
  .trivyignore
Labels: approved, size/XS, cncf-cla: yes, release-note-none

#802 fix: PRISMA-2022-0227
  go.mod
  go.sum
  vendor/github.com/emicklei/go-restful/v3/CHANGES.md
  vendor/github.com/emicklei/go-restful/v3/README.md
  vendor/github.com/emicklei/go-restful/v3/compress.go
  vendor/github.com/emicklei/go-restful/v3/constants.go
  vendor/github.com/emicklei/go-restful/v3/curly.go
  vendor/github.com/emicklei/go-restful/v3/entity_accessors.go
  vendor/github.com/emicklei/go-restful/v3/json.go
  vendor/github.com/emicklei/go-restful/v3/jsoniter.go
  vendor/github.com/emicklei/go-restful/v3/jsr311.go
  vendor/github.com/emicklei/go-restful/v3/request.go
  vendor/github.com/emicklei/go-restful/v3/response.go
  vendor/github.com/emicklei/go-restful/v3/route.go
  vendor/github.com/emicklei/go-restful/v3/route_builder.go
  vendor/modules.txt
Labels: kind/bug, size/L, release-note, approved, cncf-cla: yes

#796 chore: upgrade sidecar image versions
  charts/README.md
  charts/latest/csi-driver-smb-v0.0.0.tgz
  charts/latest/csi-driver-smb/templates/csi-smb-controller.yaml
  charts/latest/csi-driver-smb/values.yaml
  charts/v1.14.0/csi-driver-smb-v1.14.0.tgz
  charts/v1.14.0/csi-driver-smb/templates/csi-smb-controller.yaml
  charts/v1.14.0/csi-driver-smb/values.yaml
  deploy/csi-smb-controller.yaml
  deploy/csi-smb-node-windows.yaml
  deploy/csi-smb-node.yaml
  deploy/v1.14.0/csi-smb-controller.yaml
  deploy/v1.14.0/csi-smb-node-windows.yaml
  deploy/v1.14.0/csi-smb-node.yaml
Labels: kind/feature, size/M, approved, cncf-cla: yes, release-note-none

#797 make image.*.repository variables relative by default
  charts/README.md
  charts/latest/csi-driver-smb-v0.0.0.tgz
  charts/latest/csi-driver-smb/values.yaml
Labels: kind/feature, approved, lgtm, ok-to-test, cncf-cla: yes, release-note-none, size/S

#803 doc: cut v1.15.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/csi-driver-smb-v0.0.0.tgz
  charts/v1.15.0/csi-driver-smb-v1.15.0.tgz
  charts/v1.15.0/csi-driver-smb/Chart.yaml
  charts/v1.15.0/csi-driver-smb/templates/NOTES.txt
  charts/v1.15.0/csi-driver-smb/templates/_helpers.tpl
  charts/v1.15.0/csi-driver-smb/templates/csi-proxy-windows.yaml
  charts/v1.15.0/csi-driver-smb/templates/csi-smb-controller.yaml
  charts/v1.15.0/csi-driver-smb/templates/csi-smb-driver.yaml
  charts/v1.15.0/csi-driver-smb/templates/csi-smb-node-windows.yaml
  charts/v1.15.0/csi-driver-smb/templates/csi-smb-node.yaml
  charts/v1.15.0/csi-driver-smb/templates/rbac-csi-smb.yaml
  charts/v1.15.0/csi-driver-smb/values.yaml
  deploy/v1.15.0/csi-smb-controller.yaml
  deploy/v1.15.0/csi-smb-driver.yaml
  deploy/v1.15.0/csi-smb-node-windows.yaml
  deploy/v1.15.0/csi-smb-node.yaml
  deploy/v1.15.0/rbac-csi-smb.yaml
  docs/install-csi-driver-v1.15.0.md
  docs/install-smb-csi-driver.md
  pkg/smb/controllerserver_test.go
Labels: approved, size/XXL, cncf-cla: yes, kind/documentation, release-note-none

#806 fix: CVE-2024-5321
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/storage/cacher/watch_cache.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/metrics/metrics.go
  vendor/k8s.io/cloud-provider/cloud.go
  vendor/k8s.io/kubernetes/pkg/securitycontext/util.go
  vendor/k8s.io/kubernetes/test/e2e/storage/utils/create.go
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-attacher/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-health-monitor/external-health-monitor-controller/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-provisioner/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-resizer/rbac.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-snapshotter/csi-snapshotter/rbac-csi-snapshotter.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/README.md
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-driverinfo.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-plugin.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-testing.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-attacher.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-resizer.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-snapshotter.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-proxy.yaml
  vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/update-hostpath.sh
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: kind/bug, size/L, release-note, approved, cncf-cla: yes

#808 fix: revert v1.14.0 chart change
  charts/v1.14.0/csi-driver-smb-v1.14.0.tgz
  charts/v1.14.0/csi-driver-smb/templates/csi-smb-controller.yaml
  charts/v1.14.0/csi-driver-smb/values.yaml
Labels: kind/bug, approved, size/XS, cncf-cla: yes, release-note-none

#811 fix: unmount detection failure
  charts/latest/csi-driver-smb-v0.0.0.tgz
  charts/latest/csi-driver-smb/templates/csi-smb-controller.yaml
  charts/latest/csi-driver-smb/templates/csi-smb-node.yaml
Labels: kind/bug, approved, size/XS, cncf-cla: yes, release-note-none

#812 fix: tmp path mount permission issue
  charts/v1.11.0/csi-driver-smb-v1.11.0.tgz
  charts/v1.11.0/csi-driver-smb/templates/csi-smb-controller.yaml
  charts/v1.11.0/csi-driver-smb/templates/csi-smb-node.yaml
  charts/v1.12.0/csi-driver-smb-v1.12.0.tgz
  charts/v1.12.0/csi-driver-smb/templates/csi-smb-controller.yaml
  charts/v1.12.0/csi-driver-smb/templates/csi-smb-node.yaml
  charts/v1.13.0/csi-driver-smb-v1.13.0.tgz
  charts/v1.13.0/csi-driver-smb/templates/csi-smb-controller.yaml
  charts/v1.13.0/csi-driver-smb/templates/csi-smb-node.yaml
  charts/v1.14.0/csi-driver-smb-v1.14.0.tgz
  charts/v1.14.0/csi-driver-smb/templates/csi-smb-controller.yaml
  charts/v1.14.0/csi-driver-smb/templates/csi-smb-node.yaml
  charts/v1.15.0/csi-driver-smb-v1.15.0.tgz
  charts/v1.15.0/csi-driver-smb/templates/csi-smb-controller.yaml
  charts/v1.15.0/csi-driver-smb/templates/csi-smb-node.yaml
Labels: kind/bug, size/M, release-note, approved, cncf-cla: yes

#813 fix: add pv patch permission with HonorPVReclaimPolicy enabled
  charts/latest/csi-driver-smb-v0.0.0.tgz
  charts/latest/csi-driver-smb/templates/csi-smb-controller.yaml
  charts/latest/csi-driver-smb/templates/rbac-csi-smb.yaml
  charts/v1.15.0/csi-driver-smb-v1.15.0.tgz
  charts/v1.15.0/csi-driver-smb/templates/csi-smb-controller.yaml
  charts/v1.15.0/csi-driver-smb/templates/rbac-csi-smb.yaml
  deploy/csi-smb-controller.yaml
  deploy/rbac-csi-smb.yaml
  deploy/v1.14.0/rbac-csi-smb.yaml
  deploy/v1.15.0/csi-smb-controller.yaml
  deploy/v1.15.0/rbac-csi-smb.yaml
Labels: kind/bug, release-note, approved, cncf-cla: yes, size/S
