Repository kubernetes-csi/csi-driver-smb, pull requests merged in 2024-05, with the labels that each got.

#773 test: use env var for smb server configuration
  test/e2e/dynamic_provisioning_test.go
  test/e2e/suite_test.go
  test/utils/check_driver_pods_restart.sh
Labels: kind/failing-test, size/L, approved, lgtm, ok-to-test, cncf-cla: yes, release-note-none

#776 test: fix stdlib CVE due to golang v1.22.2
  .github/workflows/trivy.yaml
Labels: kind/failing-test, approved, size/XS, cncf-cla: yes, release-note-none

#777 fix: Remove stale archived volume copy before Rename
  pkg/smb/controllerserver.go
Labels: kind/bug, release-note, size/XS, lgtm, ok-to-test, cncf-cla: yes

#779 test: fix storageclass uncleaned
  test/e2e/testsuites/dynamically_provisioned_reclaim_policy_tester.go
Labels: kind/failing-test, approved, size/XS, lgtm, ok-to-test, cncf-cla: yes, release-note-none

#785 fix: windows image 1809 build failure
  cmd/smbplugin/Dockerfile.Windows
Labels: kind/bug, release-note, approved, size/XS, cncf-cla: yes

#787 cleanup: remove v1.15.0 release since windows image build is broken
  README.md
  charts/README.md
  charts/v1.15.0/csi-driver-smb-v1.15.0.tgz
  charts/v1.15.0/csi-driver-smb/Chart.yaml
  charts/v1.15.0/csi-driver-smb/templates/NOTES.txt
  charts/v1.15.0/csi-driver-smb/templates/_helpers.tpl
  charts/v1.15.0/csi-driver-smb/templates/csi-proxy-windows.yaml
  charts/v1.15.0/csi-driver-smb/templates/csi-smb-controller.yaml
  charts/v1.15.0/csi-driver-smb/templates/csi-smb-driver.yaml
  charts/v1.15.0/csi-driver-smb/templates/csi-smb-node-windows.yaml
  charts/v1.15.0/csi-driver-smb/templates/csi-smb-node.yaml
  charts/v1.15.0/csi-driver-smb/templates/rbac-csi-smb.yaml
  charts/v1.15.0/csi-driver-smb/values.yaml
  deploy/v1.15.0/csi-smb-controller.yaml
  deploy/v1.15.0/csi-smb-driver.yaml
  deploy/v1.15.0/csi-smb-node-windows.yaml
  deploy/v1.15.0/csi-smb-node.yaml
  deploy/v1.15.0/rbac-csi-smb.yaml
  docs/install-csi-driver-v1.15.0.md
  docs/install-smb-csi-driver.md
Labels: approved, size/XXL, kind/cleanup, cncf-cla: yes, release-note-none

#781 fix: Remove excessive recursive variable expansions
  Makefile
Labels: kind/bug, ok-to-test, cncf-cla: yes, release-note-none, size/S
