Repository kubernetes-csi/csi-driver-smb, pull requests merged in 2024-02, with the labels that each got.

#744 doc: add this repo to ArtifactHub
  README.md
  charts/artifacthub-repo.yml
Labels: approved, size/XS, cncf-cla: yes, kind/documentation, release-note-none

#748 test: fix github action test failure
  .github/workflows/linux.yaml
Labels: kind/failing-test, approved, size/XS, cncf-cla: yes, release-note-none

#745 fix: change node-driver-registrar image version to 2.10.0 (deploy/v1.14.0 manifests)
  deploy/v1.14.0/csi-smb-node-windows.yaml
  deploy/v1.14.0/csi-smb-node.yaml
Labels: kind/bug, approved, size/XS, lgtm, ok-to-test, cncf-cla: yes, release-note-none

#751 test: fix goveralls
  .github/workflows/linux.yaml
Labels: kind/failing-test, approved, size/XS, cncf-cla: yes, release-note-none
