Repository kubernetes-csi/csi-driver-smb, pull requests merged in 2024-09, with the labels that each got.

#831 fix: delete volume error in archive deletion mode
  pkg/smb/controllerserver.go
  pkg/smb/smb.go
Labels: kind/bug, release-note, approved, cncf-cla: yes, size/S

#836 doc: cut v1.16.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/csi-driver-smb-v0.0.0.tgz
  charts/v1.16.0/csi-driver-smb-v1.16.0.tgz
  charts/v1.16.0/csi-driver-smb/Chart.yaml
  charts/v1.16.0/csi-driver-smb/templates/NOTES.txt
  charts/v1.16.0/csi-driver-smb/templates/_helpers.tpl
  charts/v1.16.0/csi-driver-smb/templates/csi-proxy-windows.yaml
  charts/v1.16.0/csi-driver-smb/templates/csi-smb-controller.yaml
  charts/v1.16.0/csi-driver-smb/templates/csi-smb-driver.yaml
  charts/v1.16.0/csi-driver-smb/templates/csi-smb-node-windows.yaml
  charts/v1.16.0/csi-driver-smb/templates/csi-smb-node.yaml
  charts/v1.16.0/csi-driver-smb/templates/rbac-csi-smb.yaml
  charts/v1.16.0/csi-driver-smb/values.yaml
  deploy/v1.16.0/csi-smb-controller.yaml
  deploy/v1.16.0/csi-smb-driver.yaml
  deploy/v1.16.0/csi-smb-node-windows.yaml
  deploy/v1.16.0/csi-smb-node.yaml
  deploy/v1.16.0/rbac-csi-smb.yaml
  docs/install-csi-driver-v1.16.0.md
  docs/install-smb-csi-driver.md
Labels: approved, size/XXL, cncf-cla: yes, kind/documentation, release-note-none

#840 fix: chmod volume dir before deletion
  pkg/smb/controllerserver.go
Labels: kind/bug, approved, size/XS, lgtm, ok-to-test, cncf-cla: yes, release-note-none

#842 chore: upgrade golint version
  .github/workflows/static.yaml
  pkg/csi-common/utils_test.go
  pkg/smb/controllerserver.go
  pkg/smb/controllerserver_test.go
  pkg/smb/nodeserver.go
  pkg/smb/nodeserver_test.go
  pkg/smb/smb.go
  pkg/smb/smb_test.go
  test/e2e/dynamic_provisioning_test.go
Labels: size/M, approved, lgtm, ok-to-test, kind/cleanup, cncf-cla: yes, release-note-none

#843 fix: mount with 0777 in volume creation and deletion
  .github/workflows/trivy.yaml
  pkg/smb/controllerserver.go
  pkg/smb/smb.go
  pkg/smb/smb_test.go
Labels: kind/bug, size/L, approved, cncf-cla: yes, release-note-none

#847 test: fix random ut failure
  pkg/smb/smb_test.go
Labels: kind/failing-test, approved, size/XS, cncf-cla: yes, release-note-none

#849 chore: upgrade sidecar image versions
  charts/README.md
  charts/latest/csi-driver-smb-v0.0.0.tgz
  charts/latest/csi-driver-smb/values.yaml
  deploy/csi-smb-controller.yaml
  deploy/csi-smb-node-windows.yaml
  deploy/csi-smb-node.yaml
Labels: kind/feature, approved, cncf-cla: yes, release-note-none, size/S

#850 fix: remove parent dir in DeleteVolume
  pkg/smb/controllerserver.go
  pkg/smb/smb.go
  pkg/smb/smb_test.go
  test/e2e/suite_test.go
Labels: kind/bug, size/M, release-note, approved, cncf-cla: yes

#851 fix: delete volume failure due to permission issue
  pkg/smb/controllerserver.go
Labels: kind/bug, release-note, approved, size/XS, cncf-cla: yes
