Repository kubernetes-csi/csi-driver-smb, pull requests merged in 2024-11, with the labels that each got.

#860 test: fix trivy action
  .github/workflows/trivy.yaml
Labels: kind/failing-test, approved, size/XS, cncf-cla: yes, release-note-none

#863 chore: update CSI spec to v1.10.0
  go.mod
  go.sum
  pkg/csi-common/utils_test.go
  pkg/smb/controllerserver_test.go
  pkg/smb/identityserver_test.go
  pkg/smb/nodeserver.go
  pkg/smb/nodeserver_test.go
  pkg/smb/smb.go
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi_grpc.pb.go
  vendor/modules.txt
Labels: kind/feature, approved, size/XXL, cncf-cla: yes, release-note-none

#864 chore: update dependabot
  .github/dependabot.yaml
Labels: approved, kind/cleanup, cncf-cla: yes, release-note-none, size/S

#867 cleanup: remove unused livenessProbe in registrar container
  charts/latest/csi-driver-smb-v0.0.0.tgz
  charts/latest/csi-driver-smb/templates/csi-smb-node-windows.yaml
  charts/latest/csi-driver-smb/templates/csi-smb-node.yaml
  deploy/csi-smb-node-windows.yaml
  deploy/csi-smb-node.yaml
Labels: size/M, approved, kind/cleanup, cncf-cla: yes, release-note-none

#870 Chores:remove group update rule
  .github/dependabot.yaml
Labels: approved, size/XS, lgtm, cncf-cla: yes, release-note-none

#874 test: add read-only subdir e2e test
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
Labels: kind/feature, size/M, approved, lgtm, ok-to-test, cncf-cla: yes, release-note-none
